<?php

namespace COM\SchoolBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
	//search
    public function findAllOrderByName($order)
    {
        $qb = $this->createQueryBuilder('category');
		
		$qb
        ->orderBy('category.defaultName', $order)
        ;

        return $qb->getQuery()->getResult();
    }
}
