<?php

namespace COM\SchoolBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EvaluationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluationRepository extends EntityRepository
{
	public function findBySchoolNotUser($school, $user)
    {
        $qb = $this->createQueryBuilder('evaluation');

        $qb
        ->where('evaluation.school = :school')
        ->setParameter('school', $school)
		->andWhere('evaluation.user != :user')
		->setParameter('user', $user)
		->andWhere('evaluation.current = :current')
		->setParameter('current', true);

		
		$qb
        ->orderBy('evaluation.date', 'DESC')
        ;

        return $qb
        ->getQuery()
        ->getResult()
        ;
    }
}
