<?php

namespace COM\SchoolBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SchoolContactTranslateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchoolContactTranslateRepository extends EntityRepository
{
}
