<?php

namespace COM\ForumBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
	public function getLastMessageByTopicId($topic_id){
		$query = $this->_em->createQuery('SELECT m FROM COMForumBundle:Message m JOIN m.subject s JOIN s.topic t WHERE t.id = :id');
		$query->setParameter('id', $topic_id);

		// Utilisation de getSingleResult car la requête ne doit retourner qu'un seul résultat
		$messages = $query->getResult();

		/*$qb = $this->createQueryBuilder('m');

		$qb
		->where('m.subject.topic.id = :topic_id')
		->setParameter('topic_id', $topic_id)
		;*/

		// On applique notre condition sur le QueryBuilder
		//$this->whereCurrentYear($qb);

		// On peut ajouter ce qu'on veut après
		/*$qb->orderBy('m.id', 'DESC');

		$messages = $qb
		->getQuery()
		->getResult()
		;*/
		if($messages){
			return $messages[0];
		}else{
			return null;
		}
	}
}
