<?php

namespace COM\ForumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TopicIllustrationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopicIllustrationRepository extends EntityRepository
{
}
