#tinymce
stfalcon_tinymce:
    include_jquery: false
    tinymce_jquery: true
    selector: ".tinymce"
    #base_url: "http://yourdomain.com/" # this parameter may be included if you need to override the assets_base_urls for your template engine (to override a CDN base url)
    # Get current language from the parameters.ini
    language: %locale%
    # Custom buttons
    tinymce_buttons:
        stfalcon: # Id of the first button
            title: "Stfalcon"
            image: "http://stfalcon.com/favicon.ico"
    # External plugins
    external_plugins:
    #    filemanager:
    #        url: "asset[bundles/acmedemo/js/tinymce-plugin/filemanager/editor_plugin.js]"
    #    imagemanager:
    #        url: "asset[bundles/acmedemo/js/tinymce-plugin/imagemanager/editor_plugin.js]"
    theme:
        # Simple theme: same as default theme
        simple: ~
        # Advanced theme with almost all enabled plugins
        advanced:
            plugins:
                #- "advlist autolink lists link image charmap print preview hr anchor pagebreak"
                - "advlist autolink lists link image charmap preview hr anchor pagebreak"
                #- "searchreplace wordcount visualblocks visualchars code fullscreen"
                - "searchreplace wordcount visualblocks visualchars code"
                - "insertdatetime media nonbreaking save table contextmenu directionality"
                - "emoticons template paste textcolor"
            #toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
            #toolbar2: "print preview media | forecolor backcolor emoticons | stfalcon | example"
            toolbar1: "insertfile undo redo | preview code | styleselect | bold italic underline | forecolor backcolor | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media | table"
            #toolbar1: "insertfile undo redo | styleselect | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media | table | preview"
            image_advtab: true
            templates:
                - {title: 'Test template 1', content: 'Test 1'}
                - {title: 'Test template 2', content: 'Test 2'}
            menubar: false
            relative_urls: false
            convert_urls: false
        # BBCode tag compatible theme (see http://www.bbcode.org/reference.php)
        advanced_counterparty:
            plugins:
                - "advlist autolink lists link image charmap preview hr anchor pagebreak"
                - "searchreplace wordcount visualblocks visualchars code"
                - "insertdatetime media nonbreaking save table contextmenu directionality"
                - "emoticons template paste textcolor"
            toolbar1: "insertfile undo redo | styleselect | forecolor backcolor | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | image"
            image_advtab: true
            templates:
                - {title: 'Test template 1', content: 'Test 1'}
                - {title: 'Test template 2', content: 'Test 2'}
            menubar: false
            relative_urls: false
            convert_urls: false
        bbcode:
            plugins: ["bbcode, code, link, preview"]
            menubar: false
            toolbar1: "bold,italic,underline,undo,redo,link,unlink,removeformat,cleanup,code,preview"