<?php

namespace COM\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryPostRepository extends EntityRepository
{
}
