<?php

namespace COM\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
	
	//search
    public function getPostSearch($critere)
    {
        $qb = $this->createQueryBuilder('post');

        $qb
        ->where('post.defaultTitle LIKE :critere')
        ->setParameter('critere', '%'.$critere.'%')
        ->orderBy('post.date', 'DESC')
        ;

        return $qb
        ->getQuery()
        ->getResult()
        ;
    }
}
