<?php

namespace COM\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostIllustrationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostIllustrationRepository extends EntityRepository
{
}
