com_user_home:
    path:     /user
    defaults: { _controller: COMUserBundle:User:index }
com_user_register:
    path:     /register
    defaults: { _controller: COMUserBundle:User:register }
com_user_login:
    path:     /login
    defaults: { _controller: COMUserBundle:User:login }
com_user_set_new_password:
    path:     /set-new-password
    defaults: { _controller: COMUserBundle:User:setNewPassword }
com_user_set_new_password_token:
    path:     /set-new-password/{user_id}/{token}
    defaults: { _controller: COMUserBundle:User:sendNewPassword }
com_user_modify_avatar:
    path:     /user/modify-avatar
    defaults: { _controller: COMUserBundle:User:modifyAvatar }
com_user_modify_common:
    path:     /user/modify-common
    defaults: { _controller: COMUserBundle:User:editUserCommon }
com_user_modify_biography:
    path:     /user/modify-biography
    defaults: { _controller: COMUserBundle:User:editUserBiography }
com_user_modify_password:
    path:     /user/modify-password
    defaults: { _controller: COMUserBundle:User:editUserPassword }
com_user_info_popup:
    path:     /user/info-popup/{id}
    defaults: { _controller: COMUserBundle:User:infoPopup }
com_user_profile:
    path:     /user/{username}
    defaults: { _controller: COMUserBundle:User:profile }
com_user_profile_setting:
    path:     /user/{username}/setting
    defaults: { _controller: COMUserBundle:User:setting }
