com_user_home:
    path:     /user
    defaults: { _controller: COMUserBundle:User:index }
com_user_register:
    path:     /register
    defaults: { _controller: COMUserBundle:User:register }
com_user_login:
    path:     /login
    defaults: { _controller: COMUserBundle:User:login }
com_user_modify_avatar:
    path:     /user/modify-avatar
    defaults: { _controller: COMUserBundle:User:modifyAvatar }
com_user_modify_common:
    path:     /user/modify-common/{user_id}
    defaults: { _controller: COMUserBundle:User:editUserCommon }
com_user_profile:
    path:     /user/{username}
    defaults: { _controller: COMUserBundle:User:profile }
com_user_profile_setting:
    path:     /user/{username}/setting
    defaults: { _controller: COMUserBundle:User:setting }
