com_admin_home:
    path:     /
    defaults: { _controller: COMAdminBundle:Dashboard:index }

#school
com_admin_school:
    path:     /school
    defaults: { _controller: COMAdminBundle:School:index }
com_admin_school_add:
    path:     /school/add
    defaults: { _controller: COMAdminBundle:School:addSchool }
com_admin_school_edit:
    path:     /school/edit-school/{id}
    defaults: { _controller: COMAdminBundle:School:editSchool }
com_admin_school_change_logo:
    path:     /school/change-logo/{school_id}
    defaults: { _controller: COMAdminBundle:School:changeLogo }
com_admin_school_edit_common:
    path:     /school/edit-common/{id}
    defaults: { _controller: COMAdminBundle:School:editSchoolGeneral }
com_admin_school_edit_translate:
    path:     /school/edit-translate/{id}/{locale}
    defaults: { _controller: COMAdminBundle:School:editSchoolTranslate }
com_admin_school_administrator:
    path:     /school/edit-school/{school_id}/admin
    defaults: { _controller: COMAdminBundle:SchoolAdmin:index }

#blog
com_admin_blog:
    path:     /blog
    defaults: { _controller: COMAdminBundle:Blog:index }
com_admin_blog_post:
    path:     /blog/post
    defaults: { _controller: COMAdminBundle:Blog:post }
com_admin_blog_post_edit:
    path:     /blog/edit-post/{id}
    defaults: { _controller: COMAdminBundle:Blog:editPost }

#newsletter
com_admin_newsletter:
    path:     /newsletter
    defaults: { _controller: COMAdminBundle:Newsletter:index }
com_admin_newsletter_email:
    path:     /newsletter/emails
    defaults: { _controller: COMAdminBundle:Newsletter:email }
com_admin_newsletter_types:
    path:     /newsletter/types
    defaults: { _controller: COMAdminBundle:Newsletter:listNewsletter }