com_admin_home:
    path:     /
    defaults: { _controller: COMAdminBundle:Dashboard:index }

#school
com_admin_school:
    path:     /school
    defaults: { _controller: COMAdminBundle:School:index }
com_admin_school_add:
    path:     /school/add
    defaults: { _controller: COMAdminBundle:School:addSchool }
com_admin_school_edit:
    path:     /school/edit-school/{id}
    defaults: { _controller: COMAdminBundle:School:editSchool }
com_admin_school_change_logo:
    path:     /school/change-logo/{school_id}
    defaults: { _controller: COMAdminBundle:School:changeLogo }
com_admin_school_add_cover:
    path:     /school/add-cover/{school_id}
    defaults: { _controller: COMAdminBundle:School:addCover }
com_admin_school_edit_common:
    path:     /school/edit-common/{id}
    defaults: { _controller: COMAdminBundle:School:editSchoolCommon }
com_admin_school_edit_translate:
    path:     /school/edit-translate/{id}/{locale}
    defaults: { _controller: COMAdminBundle:School:editSchoolTranslate }
com_admin_school_admin:
    path:     /school/edit-school/{school_id}/admin
    defaults: { _controller: COMAdminBundle:SchoolAdmin:index }
com_admin_school_get_not_admin:
    path:     /school/edit-school/{school_id}/get-not-admin
    defaults: { _controller: COMAdminBundle:SchoolAdmin:getUsersNotAdminSchool }
com_admin_school_set_admin:
    path:     /school/edit-school/{school_id}/set-admin/{user_id}
    defaults: { _controller: COMAdminBundle:SchoolAdmin:setAdminSchool }
com_admin_school_remove_admin:
    path:     /school/edit-school/{school_id}/remove-admin/{user_id}
    defaults: { _controller: COMAdminBundle:SchoolAdmin:removeAdminSchool }
com_admin_school_contact:
    path:     /school/edit-school/{school_id}/contact
    defaults: { _controller: COMAdminBundle:SchoolContact:index }
com_admin_school_contact_add:
    path:     /school/{school_id}/contact/add
    defaults: { _controller: COMAdminBundle:SchoolContact:addContact }
com_admin_school_contact_edit:
    path:     /school/edit-contact/{contact_id}
    defaults: { _controller: COMAdminBundle:SchoolContact:editContact }
com_admin_school_contact_edit_common:
    path:     /school/edit-contact-common/{contact_id}
    defaults: { _controller: COMAdminBundle:SchoolContact:editContactCommon }
com_admin_school_contact_edit_translate:
    path:     /school/edit-contact-translate/{contact_id}/{locale}
    defaults: { _controller: COMAdminBundle:SchoolContact:editContactTranslate }
com_admin_school_subscriber:
    path:     /school/edit-school/{school_id}/subscriber
    defaults: { _controller: COMAdminBundle:SchoolSubscription:index }
com_admin_school_field:
    path:     /school/edit-school/{school_id}/field
    defaults: { _controller: COMAdminBundle:SchoolField:index }
com_admin_school_field_add:
    path:     /school/{school_id}/field/add
    defaults: { _controller: COMAdminBundle:SchoolField:addField }
com_admin_school_field_edit:
    path:     /school/edit-field/{field_id}
    defaults: { _controller: COMAdminBundle:SchoolField:editField }
com_admin_school_field_edit_common:
    path:     /school/edit-field-common/{id}
    defaults: { _controller: COMAdminBundle:SchoolField:editFieldCommon }
com_admin_school_field_edit_translate:
    path:     /school/edit-field-translate/{id}/{locale}
    defaults: { _controller: COMAdminBundle:SchoolField:editFieldTranslate }
com_admin_school_field_delete:
    path:     /school/delete-field/{id}/
    defaults: { _controller: COMAdminBundle:SchoolField:deleteField }

#blog
com_admin_blog:
    path:     /blog
    defaults: { _controller: COMAdminBundle:Blog:index }
com_admin_blog_post:
    path:     /blog/post
    defaults: { _controller: COMAdminBundle:Blog:post }
com_admin_blog_post_add:
    path:     /blog/post/add
    defaults: { _controller: COMAdminBundle:Blog:addPost }
com_admin_blog_post_edit:
    path:     /blog/edit-post/{id}
    defaults: { _controller: COMAdminBundle:Blog:editPost }
com_admin_blog_post_change_illustration:
    path:     /blog/post/change-illustration/{id}
    defaults: { _controller: COMAdminBundle:Blog:changeIllustration }
com_admin_blog_post_edit_common:
    path:     /blog/edit-common/{id}
    defaults: { _controller: COMAdminBundle:Blog:editPostCommon }
com_admin_blog_post_edit_translate:
    path:     /blog/post/edit-translate/{id}/{locale}
    defaults: { _controller: COMAdminBundle:Blog:editPostTranslate }
com_admin_blog_category:
    path:     /blog/category
    defaults: { _controller: COMAdminBundle:Blog:category }
com_admin_blog_category_add:
    path:     /blog/category/add
    defaults: { _controller: COMAdminBundle:Blog:addCategory }
com_admin_blog_category_edit:
    path:     /blog/edit-category/{id}
    defaults: { _controller: COMAdminBundle:Blog:editCategory }
com_admin_blog_category_edit_common:
    path:     /blog/category/edit-common/{id}
    defaults: { _controller: COMAdminBundle:Blog:editCategoryCommon }
com_admin_blog_category_edit_translate:
    path:     /blog/category/edit-translate/{id}/{locale}
    defaults: { _controller: COMAdminBundle:Blog:editCategoryTranslate }

#advert
com_admin_advert:
    path:     /advert
    defaults: { _controller: COMAdminBundle:Advert:index }
com_admin_advert_add:
    path:     /advert/add
    defaults: { _controller: COMAdminBundle:Advert:addAdvert }
com_admin_advert_edit:
    path:     /advert/edit-advert/{id}
    defaults: { _controller: COMAdminBundle:Advert:editAdvert }
com_admin_advert_change_illustration:
    path:     /advert/change-illustration/{id}
    defaults: { _controller: COMAdminBundle:Advert:changeIllustration }
com_admin_advert_edit_common:
    path:     /advert/edit-common/{id}
    defaults: { _controller: COMAdminBundle:Advert:editAdvertCommon }
com_admin_advert_edit_translate:
    path:     /advert/edit-translate/{id}/{locale}
    defaults: { _controller: COMAdminBundle:Advert:editAdvertTranslate }
com_admin_advert_category:
    path:     /advert/category
    defaults: { _controller: COMAdminBundle:Advert:category }
com_admin_advert_category_add:
    path:     /advert/category/add
    defaults: { _controller: COMAdminBundle:Advert:addCategory }
com_admin_advert_category_edit:
    path:     /advert/edit-category/{id}
    defaults: { _controller: COMAdminBundle:Advert:editCategory }
com_admin_advert_category_edit_common:
    path:     /advert/category/edit-common/{id}
    defaults: { _controller: COMAdminBundle:Advert:editCategoryCommon }
com_admin_advert_category_edit_translate:
    path:     /advert/category/edit-translate/{id}/{locale}
    defaults: { _controller: COMAdminBundle:Advert:editCategoryTranslate }

#forum
com_admin_forum:
    path:     /forum
    defaults: { _controller: COMAdminBundle:Forum:index }
com_admin_forum_topic_add:
    path:     /forum/add-topic
    defaults: { _controller: COMAdminBundle:Forum:addTopic }
com_admin_forum_topic_edit:
    path:     /forum/edit-topic/{id}
    defaults: { _controller: COMAdminBundle:Forum:editTopic }
com_admin_forum_topic_edit_common:
    path:     /forum/edit-topic-common/{id}
    defaults: { _controller: COMAdminBundle:Forum:editTopicCommon }
com_admin_forum_topic_edit_translate:
    path:     /forum/edit-topic-translate/{id}/{locale}
    defaults: { _controller: COMAdminBundle:Forum:editTopicTranslate }
com_admin_forum_topic_change_illustration:
    path:     /forum/topic-change-illustration/{id}
    defaults: { _controller: COMAdminBundle:Forum:changeTopicIllustration }

#user
com_admin_user:
    path:     /user
    defaults: { _controller: COMAdminBundle:User:index }
com_admin_user_edit:
    path:     /user/edit-user/{id}
    defaults: { _controller: COMAdminBundle:User:editUser }

#newsletter
com_admin_newsletter:
    path:     /newsletter
    defaults: { _controller: COMAdminBundle:Newsletter:index }
com_admin_newsletter_email:
    path:     /newsletter/emails
    defaults: { _controller: COMAdminBundle:Newsletter:email }
com_admin_newsletter_types:
    path:     /newsletter/types
    defaults: { _controller: COMAdminBundle:Newsletter:listNewsletter }