services:
    com_advert.advert_service:
        class: COM\AdvertBundle\Service\AdvertService
        arguments: ["@doctrine.orm.entity_manager"]
    com_advert.advert_extension:
        class: COM\AdvertBundle\Twig\AdvertExtension
        arguments: ["@com_advert.advert_service"]
        tags:
            - { name: twig.extension }
