<?php

namespace COM\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdvertSchoolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertSchoolRepository extends EntityRepository
{
}
