com_school_home:
    path:     /school
    defaults: { _controller: COMSchoolBundle:School:index }
com_school_add_evaluation:
    path:     /add-evaluation/{id}
    defaults: { _controller: COMSchoolBundle:School:addEvaluation }
com_school_viewbyid:
    path:     /school/{id}
    defaults:
        _controller: COMSchoolBundle:School:viewById
com_school_view:
    path:     /{slug}/{type}
    defaults:
        _controller: COMSchoolBundle:School:view
        type: about
