com_school_categories:
    path:     /school/categories
    defaults: { _controller: COMSchoolBundle:School:categories }
com_school_home:
    path:     /school/{page}
    defaults:
        _controller: COMSchoolBundle:School:index
        page: 1
com_school_add_evaluation:
    path:     /add-evaluation/{id}
    defaults: { _controller: COMSchoolBundle:School:addEvaluation }
com_school_get_map_coordonnees:
    path:     /{slug}/get-map-coordonnees
    defaults: { _controller: COMSchoolBundle:School:getMapCoordonnees }
com_school_toggle_subscription:
    path:     /school/{school_id}/toggle-subscription
    defaults: { _controller: COMSchoolBundle:School:toogleSubscription }
com_school_category_view:
    path:     /school/category/{slug}/{page}
    defaults:
        _controller: COMSchoolBundle:School:viewCategory
        page: 1
com_school_viewbyid:
    path:     /school/id/{id}
    defaults:
        _controller: COMSchoolBundle:School:viewById
com_school_view:
    path:     /{slug}/{type}
    defaults:
        _controller: COMSchoolBundle:School:view
        type: about
