services:
    com_school.school_service:
        class: COM\SchoolBundle\Service\SchoolService
        arguments: ["@doctrine.orm.entity_manager"]
    com_school.school_extension:
        class: COM\SchoolBundle\Twig\SchoolExtension
        arguments: ["@com_school.school_service"]
        tags:
            - { name: twig.extension }
