com_forum_home:
    path:     /forum
    defaults: { _controller: COMForumBundle:Forum:index }
com_forum_view_topic:
    path:     /forum/topic/{slug}
    defaults: { _controller: COMForumBundle:Forum:viewTopic }
com_forum_view_subject:
    path:     /forum/subject/{slug}
    defaults: { _controller: COMForumBundle:Forum:viewSubject }
com_forum_new_subject:
    path:     /forum/new-subject/{topic_id}
    defaults: { _controller: COMForumBundle:Forum:newSubject }
com_forum_new_message:
    path:     /forum/new-message/{subject_id}
    defaults: { _controller: COMForumBundle:Forum:newMessage }
