services:
    com_forum.forum_service:
        class: COM\ForumBundle\Service\ForumService
        arguments: ["@doctrine.orm.entity_manager"]
    com_forum.forum_extension:
        class: COM\ForumBundle\Twig\ForumExtension
        arguments: ["@com_forum.forum_service"]
        tags:
            - { name: twig.extension }