com_blog_home:
    path:     /blog
    defaults: { _controller: COMBlogBundle:Blog:index }
com_blog_load_posts:
    path:     /blog/load-post/{post_id}
    defaults: { _controller: COMBlogBundle:Blog:loadPosts }
com_blog_post_viewbyid:
    path:     /blog/id/{id}
    defaults: { _controller: COMBlogBundle:Blog:viewById }
com_blog_post_new_comment:
    path:     /blog-post/new-comment/{post_id}
    defaults: { _controller: COMBlogBundle:Blog:newComment }
com_blog_load_calendar:
    path:     /blog/load-calendar/{month}
    defaults: { _controller: COMBlogBundle:Blog:loadCalendar }
com_blog_post_load_comment:
    path:     /blog-post/load-comment/{post_id}/{comment_id}
    defaults: { _controller: COMBlogBundle:Blog:loadComments }
com_blog_post_set_post_school:
    path:     /blog-post/set-post-school/{post_id}/{school_id}
    defaults: { _controller: COMBlogBundle:Blog:setPostSchool }
com_blog_category:
    path:     /blog/category
    defaults: { _controller: COMBlogBundle:Blog:category }
com_blog_category_view:
    path:     /blog/category/{slug}
    defaults: { _controller: COMBlogBundle:Blog:viewCategory }
com_blog_category_view_load_posts:
    path:     /blog/category/{slug}/load-post/{post_id}
    defaults: { _controller: COMBlogBundle:Blog:loadPostsCategory }
com_blog_view:
    path:     /blog/{slug}
    defaults: { _controller: COMBlogBundle:Blog:view }
