com_blog_home:
    path:     /blog
    defaults: { _controller: COMBlogBundle:Blog:index }
com_blog_view:
    path:     /blog/{slug}
    defaults: { _controller: COMBlogBundle:Blog:view }
com_blog_post_viewbyid:
    path:     /blog/id/{id}
    defaults: { _controller: COMBlogBundle:Blog:viewById }
com_blog_post_new_comment:
    path:     /blog-post/new-comment/{post_id}
    defaults: { _controller: COMBlogBundle:Blog:newComment }
com_blog_post_load_comment:
    path:     /blog-post/load-comment/{post_id}/{comment_id}
    defaults: { _controller: COMBlogBundle:Blog:loadComments }
com_blog_post_set_post_school:
    path:     /blog-post/set-post-school/{post_id}/{school_id}
    defaults: { _controller: COMBlogBundle:Blog:setPostSchool }
