<?php

namespace COM\AdvertBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends EntityRepository
{
	
	//search
    public function getAdvertSearch($critere)
    {
        $qb = $this->createQueryBuilder('advert');

        $qb
        ->where('advert.defaultTitle LIKE :critere')
        ->setParameter('critere', '%'.$critere.'%')
        ->orderBy('advert.date', 'DESC')
        ;

        return $qb
        ->getQuery()
        ->getResult()
        ;
    }
}
