<?php

namespace COM\AdvertBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdvertTranslateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertTranslateRepository extends EntityRepository
{
}
